- name: add vscode repo apt key
  become: yes
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: add vscode deb repo
  become: yes
  apt_repository:
    repo: deb https://packages.microsoft.com/repos/vscode stable main
    state: present

- name: install vscode
  become: yes
  apt:
    update_cache: yes
    state: latest
    name: code