- name: update apt cache and dist
  become: yes
  apt:
    update_cache: yes
    upgrade: dist

- name: install packages
  become: yes
  apt:
    state: latest
    name: "{{ packages }}"
  vars:
    packages:
    - gnupg
    - pinentry-gtk2
    - tmux
    - htop
    - autossh
    - x11-apps
    - apt-transport-https
    - ca-certificates
    - curl
    - jq
    - gnupg2
    - software-properties-common
    - file
    - dnsutils
    - wget
    - python-pip
    - python3
    - python3-pip
    - asciinema

- include_tasks: crostini.yaml
  when: ansible_distribution_release|lower != 'rodete'