- name: gpg-agent pinentry program
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.gnupg/gpg-agent.conf"
    line: "pinentry-program /usr/bin/pinentry-gtk-2"
    regexp: "^pinentry-program.*"
    create: yes

- name: gpg tty
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "export GPG_TTY=$(tty)"