- name: check terraform install
  stat:
    path: /usr/local/bin/terraform
  register: terraform_st

- name: check terraform version
  shell: terraform version | head -1
  register: terraform_ver
  changed_when: no
  when: terraform_st.stat.exists

- name: install terraform
  become: yes
  unarchive:
    src: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
    dest: /usr/local/bin/
    remote_src: yes
  when: not terraform_st.stat.exists or terraform_version not in terraform_ver.stdout