projects: "{{ ansible_env.HOME }}/projects"
debian_release: stretch
golang_version: 1.11.1
dep_version: v0.5.0
kubectl_version: v1.12.0
skaffold_version: v0.15.1
kustomize_version: 1.0.8
helm_version: 2.11.0
terraform_version: 0.11.10