projects: "{{ ansible_env.HOME }}/projects"
debian_release: stretch
golang_version: 1.11.1
dep_version: v0.5.0
kubectl_version: v1.12.0

# https://github.com/GoogleContainerTools/skaffold/releases
skaffold_version: v0.20.0

# https://github.com/kubernetes-sigs/kustomize/releases
kustomize_version: 1.0.11

# https://github.com/helm/helm/releases
helm_version: 2.12.2

# https://www.terraform.io/downloads.html
terraform_version: 0.11.10

# https://code.visualstudio.com/docs/?dv=linux64_deb
vscode_version: 1.30.2