- name: check kubectl install
  stat:
    path: /usr/local/bin/kubectl
  register: kubectl_st

- name: check kubectl version
  shell: /usr/local/bin/kubectl version --client --short
  register: kubectl_ver
  changed_when: no
  when: kubectl_st.stat.exists

- name: install kubectl
  become: yes
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: 0755
    force: yes
  when: not kubectl_st.stat.exists or kubectl_version not in kubectl_ver.stdout

- name: check kustomize install
  stat:
    path: /usr/local/bin/kustomize
  register: kustomize_st

- name: check kustomize version
  shell: kustomize version
  register: kustomize_ver
  changed_when: no
  when: kustomize_st.stat.exists

- name: install kustomize
  become: yes
  get_url:
    url: https://github.com/kubernetes-sigs/kustomize/releases/download/v{{ kustomize_version}}/kustomize_{{ kustomize_version }}_linux_amd64
    dest: /usr/local/bin/kustomize
    mode: 0755
    force: yes
  when: not kustomize_st.stat.exists or kustomize_version not in kustomize_ver.stdout

- name: check skaffold install
  stat:
    path: /usr/local/bin/skaffold
  register: skaffold_st

- name: check skaffold version
  shell: skaffold version
  register: skaffold_ver
  changed_when: no
  when: skaffold_st.stat.exists

- name: install skaffold
  become: yes
  get_url:
    url: https://github.com/GoogleContainerTools/skaffold/releases/download/{{ skaffold_version }}/skaffold-linux-amd64
    dest: /usr/local/bin/skaffold
    mode: 0755
    force: yes
  when: not skaffold_st.stat.exists or skaffold_version not in skaffold_ver.stdout

- name: check helm install
  stat:
    path: /usr/local/bin/linux-amd64/helm
  register: helm_st

- name: check helm version
  shell: helm version -c
  register: helm_ver
  changed_when: no
  when: helm_st.stat.exists

- name: install helm
  become: yes
  unarchive:
    src: https://storage.googleapis.com/kubernetes-helm/helm-v{{ helm_version }}-linux-amd64.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
  when: not helm_st.stat.exists or helm_version not in helm_ver.stdout

- name: link helm
  become: yes
  file:
    src: /usr/local/bin/linux-amd64/helm
    dest: /usr/local/bin/helm
    state: link